### PR TITLE
Newer python versions

### PR DESCRIPTION
**Pull request by gforcada**
I hope I got it right, I'm no expert on `tox` nor in GHA 😅

### CODE REVIEW

**Comment by icemac** [comment]
Usually we use [meta/config](https://github.com/zopefoundation/meta/tree/master/config) to do such updates. But I see this repository initially has to be configured to use it. But using `meta/config` you neither have to be a tox nor a GHA expert. :Sri

**Comment by dataflake** [comment]
Tests for this package have been failing for a long time and there is no fix yet. It makes no sense to publish new packages and thereby suggest that this package is OK or it can be trusted right now.

**Comment by gforcada** [comment]
Seems that pinning to ZODB 5.6.0 and removing Python 3.6, which is anyway EOL, fixes the tests 🤞🏾 🍀  I will prepare a new PR for it

**Comment by dataflake** [comment]
Pinning ZODB to one specific version will immediately clash with any buildout that relies on Zope's own version pins. I don't see the sense in that.

**Pull request closed without merging**
